In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket indexing and selection

In [4]:
arr[9]

9

In [5]:
arr[1:5]

array([1, 2, 3, 4])

## Broadcasting

In [6]:
## Setting a value with index range --> Broadcasting

arr[0:5] = 100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arrcp = arr.copy()

arrcp

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D array

arr[row, col]

In [14]:
arr2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2d[1]

array([4, 5, 6])

In [16]:
arr2d[1][0]

4

In [17]:
arr2d[1,0]

4

### Slicing 2D array

In [18]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

## Selection

In [19]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [21]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])