In [1]:
!pip install numpy

# Numpy
https://numpy.org/


In [2]:
import numpy as np

## Creating Numpy arrays

* Vector - Strictly 1-D arrays
* Matrix - 2-d but it can still have one row and one column

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [7]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods


#### arange : Returns evenly spaced values within a given intervL

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

#### Generate an array of zeros and ones

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace : Returns evenly spaced numbers over specified interval

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye : returns an identity matrix

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random Number generation

* rand - Creates and arrya of a given shape and populates it with random samples having uniform distribution over 0 and 1.

In [22]:
np.random.rand(2)

array([0.02746243, 0.97090229])

In [23]:
np.random.rand(5,5)

array([[0.36844317, 0.13419684, 0.12685932, 0.29342802, 0.8177187 ],
       [0.26552087, 0.29210016, 0.76778769, 0.05896958, 0.19802036],
       [0.10561103, 0.07847096, 0.77052893, 0.26449447, 0.9821193 ],
       [0.37641294, 0.38561739, 0.56087745, 0.40896704, 0.14706356],
       [0.02116957, 0.15295661, 0.55922541, 0.52622803, 0.13273203]])

* randn : Returns a sample from the "standard normal distribution"

In [24]:
np.random.randn(5,5)

array([[ 1.40955899, -1.05123645,  0.44805341,  0.82102959,  1.23986849],
       [-1.90400656, -0.55961668,  0.9714293 , -0.6846954 ,  0.71079398],
       [-0.49151919, -0.80961317,  0.68091208, -1.34775424,  0.34990814],
       [-0.76757338, -0.08539305, -0.72361262, -1.02923555,  0.30897112],
       [-1.07903515,  0.89606675,  0.86775625, -1.6635687 ,  0.33823614]])

In [25]:
np.random.randint(0,50,10)

array([19, 40,  0, 38, 17, 23, 24, 49, 38, 22])

In [26]:
np.random.seed

<function RandomState.seed>

## Array attributes and methods

In [27]:
arr = np.arange(25)

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr

array([40, 48, 11, 47, 34, 45,  7,  8, 22, 33])

## Reshape

Returns and array containing the same data with a new shape

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min - 
max and min values

### argmax, argmin -
index of max and min values

In [32]:
ranarr 

array([40, 48, 11, 47, 34, 45,  7,  8, 22, 33])

In [33]:
ranarr.max()

48

In [34]:
ranarr.min()

7

In [35]:
ranarr.argmax()

1

In [36]:
ranarr.argmin()

6

## Shape

Shape is an attribute that arrays have

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
# Vector
arr.shape

(25,)

In [44]:
x = arr.reshape(1,25)

In [46]:
x.shape

(1, 25)

In [47]:
y=arr.reshape(25,1)

In [48]:
y

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
y.shape

(25, 1)

In [50]:
arr.dtype

dtype('int64')